# simple blank with shrinkwrapped minimal deps
done
- ye olde deps
todo
- make it work again but not very much 
0.1 intentially blank currently.. but has a structure.
0.2 Update deps and code to work...
1. Erase commits and reorder so its tagged progression.
2. Complete all un-opionated blanks....
3. Minimise files.... but keep nice blank structure.. 
4. indicate what needs "completing" to make it work..
4.1 use adventure or curses style fun menus or just a prompt...
